export interface ReportSection {
  title: { ar: string; en: string };
  content: { ar: string; en: string };
  charts?: any[];
  tables?: any[];
}

export interface BilingualReport {
  sections: ReportSection[];
  executiveSummary: any;
  charts: any[];
  downloadUrls: {
    pdf: string | null;
    word: string | null;
    excel: string | null;
    ppt: string | null;
  };
}

export function generateBilingualReport(
  analysisResults: any,
  companyInfo: any,
  language: 'ar' | 'en'
): BilingualReport {
  const t = (ar: string, en: string) => (language === 'ar' ? ar : en);
  
  const sections: ReportSection[] = [
    {
      title: { ar: 'الملخص التنفيذي', en: 'Executive Summary' },
      content: {
        ar: `تحليل مالي شامل لشركة ${companyInfo.name} في قطاع ${companyInfo.sector}. تم إجراء ${analysisResults.analyses?.length || 0} تحليل مالي متقدم لتقييم الأداء المالي والوضع الاستثماري.`,
        en: `Comprehensive financial analysis for ${companyInfo.name} in the ${companyInfo.sector} sector. ${analysisResults.analyses?.length || 0} advanced financial analyses were conducted to assess financial performance and investment position.`
      }
    },
    {
      title: { ar: 'التحليل الهيكلي للقوائم المالية', en: 'Structural Analysis of Financial Statements' },
      content: {
        ar: 'يستعرض هذا القسم التحليل الرأسي والأفقي للقوائم المالية مع التركيز على توزيع الأصول والخصوم وحقوق الملكية.',
        en: 'This section presents vertical and horizontal analysis of financial statements with focus on distribution of assets, liabilities, and equity.'
      }
    },
    {
      title: { ar: 'تحليل النسب المالية', en: 'Financial Ratios Analysis' },
      content: {
        ar: 'تحليل شامل للنسب المالية الأساسية مقسمة إلى خمس فئات: نسب السيولة، نسب النشاط، نسب المديونية، نسب الربحية، ونسب السوق.',
        en: 'Comprehensive analysis of key financial ratios divided into five categories: liquidity ratios, activity ratios, leverage ratios, profitability ratios, and market ratios.'
      }
    },
    {
      title: { ar: 'تحليل التدفقات النقدية', en: 'Cash Flow Analysis' },
      content: {
        ar: 'تقييم مصادر واستخدامات النقدية مع التركيز على التدفقات التشغيلية والاستثمارية والتمويلية.',
        en: 'Assessment of cash sources and uses with focus on operating, investing, and financing cash flows.'
      }
    },
    {
      title: { ar: 'التحليل المقارني المتقدم', en: 'Advanced Comparative Analysis' },
      content: {
        ar: 'مقارنة الأداء مع متوسطات الصناعة والشركات المماثلة في نفس القطاع والنشاط.',
        en: 'Performance comparison with industry averages and similar companies in the same sector and activity.'
      }
    },
    {
      title: { ar: 'تحليل التقييم والاستثمار', en: 'Valuation and Investment Analysis' },
      content: {
        ar: 'تقييم القيمة العادلة للشركة باستخدام طرق متعددة مثل صافي القيمة الحالية ومعدل العائد الداخلي.',
        en: 'Fair value assessment using multiple methods such as net present value and internal rate of return.'
      }
    },
    {
      title: { ar: 'تحليل المخاطر', en: 'Risk Analysis' },
      content: {
        ar: 'تحديد وتقييم المخاطر المالية والتشغيلية والسوقية مع اقتراحات للحد منها.',
        en: 'Identification and assessment of financial, operational, and market risks with mitigation suggestions.'
      }
    },
    {
      title: { ar: 'التوصيات الاستراتيجية', en: 'Strategic Recommendations' },
      content: {
        ar: 'توصيات مبنية على التحليل الشامل لتحسين الأداء المالي وتعزيز القيمة للمساهمين.',
        en: 'Recommendations based on comprehensive analysis to improve financial performance and enhance shareholder value.'
      }
    }
  ];

  const charts = analysisResults.analyses?.map((analysis: any) => ({
    id: analysis.id,
    title: analysis.name,
    type: 'bar',
    data: [
      { name: t('الشركة', 'Company'), value: analysis.value },
      { name: t('المعيار', 'Benchmark'), value: analysis.benchmark }
    ]
  })) || [];

  return {
    sections,
    executiveSummary: analysisResults,
    charts,
    downloadUrls: {
      pdf: null, // Will be generated by actual PDF generator
      word: null, // Will be generated by actual Word generator
      excel: null, // Will be generated by actual Excel generator
      ppt: null // Will be generated by actual PPT generator
    }
  };
}
